config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # par défaut nous sommes dans le cas du renter :
  resources :houses, only: [:index, :show] do
    resources :bookings, only: [:index, :show, :create, :edit, :update, :destroy]
  end

  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
    resources :guests, only: [:index, :show, :edit, :update, :destroy]
  end

  # profile utilisateur
  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :house
  belongs_to :user
  has_many :guests, dependent: :destroy
end

#  pour guest : dependent : :destroy du booking_id
  # class Portfolio < ApplicationRecord
  #     has_many :technologies, dependent: :destroy
  #     accepts_nested_attributes_for :technologies,

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :booking
end

app/models/house.rb
class House < ApplicationRecord
  has_many :bookings
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings # as renter
  # has_many :costumes # as owner
  has_many :received_bookings, through: :houses, source: :bookings #booking as an owner

  has_many :guests

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
skip_before_action :authenticate_user!, only: :index

  def index
    @bookings = current_user.bookings
    @bookings = Booking.all


# tri par dates
    # @ordered_bookings = @bookings.sort{|a,b| b.date <=> a.date}

    # @yearly_grouped_bookings = @ordered_bookings.group_by{|booking| booking.date.year }
#     start_date =
#     start_time = Time.new(2013,1)
# end_time = Time.new(2014,1)
# TimeDifference.between(start_time, end_time).in_minutes
  end

  def show
    @booking = Booking.find(params[:id])

    #@ordered_bookings = @bookings.sort{|a,b| b.date <=> a.date}
  end

  def create
    @house = House.find(params[:house_id])
    @booking = Booking.new(booking_params)

    @booking.house = @house
    @booking.user = current_user

    if @booking.save
      redirect_to bookings_path(@house)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)

    redirect_to bookings_path(@house)
  end

  def destroy
    # @booking = Booking.find(params[:id])
    # @booking.destroy

    Booking.destroy(params[:id])
    redirect_to bookings_path
  end


  private

  def booking_params
    params.require(:booking).permit(:start_on, :end_on)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
 before_action :authenticate_user!, only: [:index, :show]

  def index
    @guests = guest.all
  end

  def show
    @guest = Guest.find(params[:id])
    @booking = Booking.new # On crée un objet vide pour simple_form
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
 before_action :authenticate_user!, only: [:index, :show]

  def index
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
    @booking = Booking.new # On crée un objet vide pour simple_form
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="update" style="text-align: center">
    <h2>Modifier les dates</h2>
    <%= image_tag "calendrier.png", height: 200 %>


    <!-- toastui -->
    <div id="menu">
        <span id="menu-navi">
          <button type="button" class="btn btn-default btn-sm move-today" data-action="move-today">Today</button>
          <button type="button" class="btn btn-default btn-sm move-day" data-action="move-prev">
            <i class="calendar-icon ic-arrow-line-left" data-action="move-prev"></i>
          </button>
          <button type="button" class="btn btn-default btn-sm move-day" data-action="move-next">
            <i class="calendar-icon ic-arrow-line-right" data-action="move-next"></i>
          </button>
        </span>
        <span id="renderRange" class="render-range"></span>
    </div>

    <div id="calendar"></div>


    <!-- <div id="calendar" style="height: 800px;">
    </div> -->

<!-- Flatpicker shared yield  houses/show.html.erb-->
<!--     <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
 -->
     <!--flatpickr--> <!--  <%= simple_form_for [@house, @booking] do |f| %>
        <%= f.input :start_on, as: :string, required: false, input_html: {id: "start_date"} %>
        <%= f.input :end_on, as: :string, required: false, input_html: {id: "end_date"} %>
        <%= f.button :submit, "Update", class: "btn btn-danger btn-block" %>
      <% end %>
    </div>-->
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="index-title text-center">
    <h1>List of all the bookings</h1>
  </div>

  <div class="row">
<!--
tri par dates
faire une partial pour booking à la place de room card comme ds partypix
 -->


    <% @bookings.each do |booking| %>
      <div class="col-xs-12 col-sm-4 col-sm-offset-1 list-inline">

        <div class="flatcard card-container text-center">

          <p>Du <%= booking.start_on %> au <%= booking.end_on %></p>

          <p><%= booking.house.name %> by <strong><%= booking.user.name %></strong></p>

          <%= link_to edit_booking_path(booking), class: "bottom-menu-element" do %>
            <i class="fas fa-edit fa-1x bottom-menu-img"> Edit booking</i>

          <% end %>

          <%= link_to booking_path(booking), method: :delete,
            data: { confirm: "Are you sure ?" }, class: "bottom-menu-element" do %>
            <i class="fas fa-trash-alt fa-1x bottom-menu-img">  Delete Booking</i>

          <% end %>

        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/bookings/show.html.erb
<!-- page inutile ?


<div class="container">
  <div class="update" style="text-align: center">
    <h2> thanks to update your booking</h2>
      <h3><%= @house.name %></h3>

      <%= simple_form_for [@house, @booking] do |f| %>
        <div class="form-inputs col-xs-8 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3" >
          <%= f.input :start_on %>
          <%= f.input :end_on %>
        </div>

        <div class="form-actions col-xs-8 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3" >
          <%= f.submit "Save", class: "btn btn-primary btn-block" %>
        </div>
      <% end %>
    <%= image_tag "calendrier.png", height: 200 %>
  </div>
</div>

 -->

app/views/houses/index.html.erb
<div class="container text-center">
  <h1>Choix de la maison  </h1>
  <div class="list-houses">
    <div class="row">
      <% @houses.each do |house| %>
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 list-inline">

          <div class="flatcard card-container">

            <h2><%= house.name %></h2>

            <div class="photo">

              <%= image_tag "maison.jpg", height:200; %>
            </div>
            <%= link_to "Réservez-moi !", house_path(house), class: "btn btn-danger btn-block" %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/houses/show.html.erb
<div class="container">
  <div class="select" style="text-align: center">
    <h2> Veuillez sélectionner les dates</h2>
    <%= image_tag "calendrier.png", height: 200 %>
  </div>
<!-- toast ui -->
 <!-- toastui -->


    <div id="calendar">
      <div id="menu">
        <span id="menu-navi">
          <button type="button" class="btn btn-default btn-sm move-today" data-action="move-today">Today</button>
          <button type="button" class="btn btn-default btn-sm move-day" data-action="move-prev">
            <i class="calendar-icon ic-arrow-line-left" data-action="move-prev"></i>
          </button>
          <button type="button" class="btn btn-default btn-sm move-day" data-action="move-next">
            <i class="calendar-icon ic-arrow-line-right" data-action="move-next"></i>
          </button>
        </span>
        <span id="renderRange" class="render-range"></span>
      </div>
    <h3>
      <%= @house.name.capitalize %>
    </h3>
    <!-- flatpicker -->
    <%= simple_form_for [@house, @booking] do |f| %>
      <%= f.input :start_on, as: :string, required: false, input_html: {id: "start_date"} %>
      <%= f.input :end_on, as: :string, required: false, input_html: {id: "end_date"} %>
      <%= f.button :submit, "Réserver", class: "btn btn-success btn-block" %>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Neuvic</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>



    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<!--  flatpickr
    <script src="https://npmcdn.com/flatpickr/dist/flatpickr.min.js"></script>
    <script src="https://npmcdn.com/flatpickr/dist/l10n/ru.js"></script>
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_green.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script> -->

<!-- toast ui -->



<!-- pied de page et home page -->
  <!--   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> -->



  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<html>
  <body>

    <div class="banner text-center"
  style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.2) 20%, rgba(0,0,0,0.2) 20%),
  url(<%= image_path 'maison.jpg' %>)">

      <h1>Bienvenue !</h1>
      <p>Petite application pour renseigner les dates de vacances à Neuvic, afin de savoir qui est là et quand. </p>
      <%= link_to "Commencer", houses_path, class: "btn btn-danger btn-lg"  %>
    </div>

      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="card">
           <%= image_tag "briefcase.png", height: 100 %>
          <h2>Rapide</h2>
          <p>Une app <strong>rapide,</strong> très rapide</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="card">
            <%= image_tag "diamond.png", height: 100 %>
            <h2>Simple</h2>
            <p>Une app, <strong>simple,</strong> très simple</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="card">
            <%= image_tag "heart.png", height: 100 %>
            <h2>Pratique</h2>
            <p>Une app, <strong>pratique, </strong> très pratique</p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="card">
            <%= image_tag "laptop.png", height: 100 %>
            <h2>Jolie</h2>
            <p>Une app, <strong>jolie,</strong> très jolie</p>
          </div>
        </div>
      </div>
    </div>

    <div id="footer">
      <p>Copyright Benoît Mathonat SAS. 2018. Tout droit réservés</p>
      <ul class="list-inline">
        <li><a href="#"><i class="fa fa-youtube"></i></a></li>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
      </ul>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Houses", houses_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>

<!--       <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
 -->
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "background.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li> <%= link_to "Houses", houses_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li>      <%= link_to "My bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %></li>
      </ul>
    </div>
  </div>
</div>